export enum tagTypes {
  user = "user",
  super_admin = "super_admin",
  admin = "admin",
  driver = "driver",
  helper = "helper",
  brand = "brand",
  model = "model",
  vehicle = "vehicle",
  party = "party",
  trip = "trip",
  accountType = "accountType",
  accountHead = "accountHead",
  expenseHead = "expenseHead",
  expense = "expense",
  fuelType = "fuelType",
  fuelStation = "fuelStation",
  fuel = "fuel",
  uom = "uom",
  equipment = "equipment",
  equipmentIn = "equipmentIn",
  maintenanceHead = "maintenanceHead",
  maintenance = "maintenance",
  accidentHistory = "accidentHistory",
  paperWork = "paperWork",
  conversation = "conversation",
  conversations = "conversations",
  message = "message",
  messages = "messages",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.super_admin,
  tagTypes.admin,
  tagTypes.driver,
  tagTypes.helper,
  tagTypes.brand,
  tagTypes.model,
  tagTypes.vehicle,
  tagTypes.party,
  tagTypes.trip,
  tagTypes.accountType,
  tagTypes.accountHead,
  tagTypes.expenseHead,
  tagTypes.expense,
  tagTypes.fuelType,
  tagTypes.fuelStation,
  tagTypes.fuel,
  tagTypes.uom,
  tagTypes.equipment,
  tagTypes.equipmentIn,
  tagTypes.maintenanceHead,
  tagTypes.maintenance,
  tagTypes.accidentHistory,
  tagTypes.paperWork,
  tagTypes.conversation,
  tagTypes.conversations,
  tagTypes.message,
  tagTypes.messages,
];
